### PR TITLE
Externalizing the config

### PR DESCRIPTION
**Pull request by gopivaibhav**
Signed-off-by: Gopi Vaibhav <gopivaibhav0@gmail.com>

**Description**

This PR fixes:
- Taking out the meshmodel metadata configuration from .go file to a JSON file for easier updation of Metadata.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Revolyssup** [comment]
@gopivaibhav Please look at the failing lint check.
Replace `defer f.Close()` with
`	defer func() {
		if err := f.Close(); err != nil {
			fmt.Printf("Error closing file: %s\n", err)
		}
	}()`

**Comment by Revolyssup** [comment]
@gopivaibhav Make sure you don't create a pull request with your master branch. Create a separate branch for your PR.

**Comment by gopivaibhav** [comment]
> @gopivaibhav Make sure you don't create a pull request with your master branch. Create a separate branch for your PR.

Thanks for letting me know, I actually do with the different branch but forgot to do so here

**Comment by gopivaibhav** [comment]
> @gopivaibhav Please look at the failing lint check. Replace `defer f.Close()` with ` defer func() { if err := f.Close(); err != nil { fmt.Printf("Error closing file: %s\n", err) } }()`

I have changed this to pass the lint checks

**Comment by leecalcote** [comment]
Good deal, @gopivaibhav.

@gr455 Look good?

**Comment by gr455** [comment]
Seems like a harmless change. Needs to be propagated to all the other adapters.

**Comment by leecalcote** [comment]
@gopivaibhav yay! 🎉

**Pull request merged**
