### PR TITLE
[Patterns] generate components with mesh name

### PR DESCRIPTION
**Pull request by DelusionalOptimist**
Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**
Now generates components with name of the service mesh to preserve unique identity.
These diffs look a bit odd because git got confused due to similar content in files.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 

Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>

### CODE REVIEW

**Comment by DelusionalOptimist** [comment]
@sayantan1413 FYI

**Comment by leecalcote** [comment]
@utkarsh-pro looks good?

**Review by sayantan1413 — APPROVED** [review]
LGTM. I have also used the same logic in OSM and everything works fine and in this PR also I think we are getting out desired result with the mesh name appended with the resources.

**Comment by leecalcote** [comment]
Quick check - this will be updated with a splitting of object type and mesh type, right?

**Comment by utkarsh-pro** [comment]
@DelusionalOptimist let's update this to conform with the design spec?

**Comment by DelusionalOptimist** [comment]
sorry. got stuck with stuff over the weekend. updating it ASAP.

**Comment by DelusionalOptimist** [comment]
Generated templates: https://github.com/DelusionalOptimist/meshery-istio/tree/oam-gen-tests/templates/oam/workloads/workloads-1.9.7
Schemas: https://github.com/DelusionalOptimist/meshery-istio/blob/0dd067247177909110d32a4459939e7d282fae46/templates/oam/workloads/workloads-1.9.7/envoyfilter.istio.meshery.layer5io.schema.json#L294-L296
Workload defs: https://github.com/DelusionalOptimist/meshery-istio/blob/0dd067247177909110d32a4459939e7d282fae46/templates/oam/workloads/workloads-1.9.7/envoyfilter.istio_definition.json#L8-L18

**Comment by utkarsh-pro** [comment]
@DelusionalOptimist I think for some reason `k8sApiVersion` is being set to `null` in the definition. It should rather be set to the API Version of that resource, like `istio.xyz/v1alpha3`. 

Also, `k8sKind` is supposed to be the Kind of the resource, for example Envoy Filter will have it set to `EnvoyFilter`.

**Comment by DelusionalOptimist** [comment]
> @DelusionalOptimist I think for some reason `k8sApiVersion` is being set to `null` in the definition. It should rather be set to the API Version of that resource, like `istio.xyz/v1alpha3`.

Yeah left that intentionally cuz I was unsure about it being version of k8s extensions API version or the resource version. Cool, will update it now :+1: 

> Also, `k8sKind` is supposed to be the Kind of the resource, for example Envoy Filter will have it set to `EnvoyFilter`.

Gotcha :+1:

**Comment by DelusionalOptimist** [comment]
@utkarsh-pro Good to go?
https://github.com/DelusionalOptimist/meshery-istio/tree/oam-gen-tests/templates/oam/workloads/workloads-1.9.7

**Comment by utkarsh-pro** [comment]
@DelusionalOptimist looks great! :raised_hands: 

Just a  merge conflict to resolve I guess

**Pull request merged**
