### PR TITLE
Fixes Light/Dark Mode images + slack + community logos in Readme.

### LINKED ISSUE #465: [Docs] README: Light Mode / Dark Mode support
**Current Behavior**
This repo's readme.md (https://github.com/layer5io/layer5#readme) assumes light mode visitors.

**Desired Situation**
Use GitHub's relatively new ability to [define light and dark mode images](https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/) in markdown for each of the logos.

Find light and dark mode flavors of each of the logos here: https://layer5.io/brand or in the shared, community drive.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by legendarykamal**
**Description**

This PR fixes #465

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Thanks. :)

**Comment by legendarykamal** [comment]
Welcome  🛩️  I think the congrats image is broken, lets fix it.

**Comment by leecalcote** [comment]
🛩️ 🔥

**Comment by legendarykamal** [comment]
here we go https://github.com/meshery/meshery-istio/pull/507

**Pull request merged**
