### PR TITLE
changed path of workflow

### PR DESCRIPTION
**Pull request by siddhikhapare**
Signed-off-by: siddhikhapare <siddhikhapare66@bvcoenm.edu.in>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Revolyssup** [comment]
@asubedy  Do you think this change will require some changes in the markdown generation step as well? To me it doesn't look as if it will required given we just pick on filenames and not whats inside. But just wanted to confirm since you wrote the script.

**Comment by siddhikhapare** [comment]
@leecalcote @asubedy @Revolyssup setting up minikube  failed on ubuntu machine
Are these actions checking based on service mesh patterns?

**Comment by leecalcote** [comment]
> @asubedy Do you think this change will require some changes in the markdown generation step as well? To me it doesn't look as if it will be required given we just pick on filenames and not whats inside. But just wanted to confirm since you wrote the script.

@asubedy reminder

**Comment by asubedy** [comment]
No need to modify the markdown generation file just the change of file path should be enough

**Review by asubedy — APPROVED** [review]
LGTM 👍

**Pull request merged**
