### PR TITLE
Update ISTIO to Istio

### LINKED ISSUE #609: Move from ISTIO to Istio in model components
<@U02T9JKCRLG> when you get the Meshery Adapters registering their components again, will you please see that “ISTIO” change to “Istio” in the Istio adapter’s components?

[Slack Message](https://layer5io.slack.com/archives/C017NA80S66/p1692045330887179)

### Implementation:

1. Find "ISTIO" and replace with "Istio".

### Acceptance Test:

1. Meshery Adapter registers components with Meshery Server.
1. User is able to provision Istio when using the renamed components.

### PR DESCRIPTION
**Pull request by Freedisch**
**Description**

This PR fixes #609

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by MUzairS15 — CHANGES_REQUESTED** [review]
@Freedisch Under `/templates` folder as well.

**Comment by MUzairS15** [comment]
@Freedisch any  update?

**Comment by Freedisch** [comment]
> @Freedisch Under `/templates` folder as well.

got it

**Comment by Freedisch** [comment]
@MUzairS15 , there is not reference under of that under the template folder

**Comment by Chadha93** [comment]
@MUzairS15 You might want to takeover this...

**Pull request closed without merging**
