### PR TITLE
removed extra metdata from pre-generated components

### LINKED ISSUE #284: remove extra metdata from pre-generated components
**Description**
["Object-type", "Version" etc](https://github.com/meshery/meshery-istio/blob/491b956311f93e6cba66aa20e180b0944a2e6ee4/templates/oam/workloads/1.10.0/envoyfilter.istio.meshery.layer5io.schema.json#L295-L297) are not supposed to be in the json schema for pattern components.

### PR DESCRIPTION
**Pull request by sayantan1413**
Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>

**Description**

remove extra metdata from pre-generated components

This PR fixes #284 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Done?

**Comment by leecalcote** [comment]
Yoo-hoo, @sayantan1413. 🙂  The issue that this PR closes went stale... is this something that you'll be able to take another look at and wrap up this week? 😅

**Comment by sayantan1413** [comment]
Yes, @leecalcote I will complete this PR this week.

**Comment by leecalcote** [comment]
Thank you. Yes, please.

**Comment by leecalcote** [comment]
@Revolyssup can you see this one through?

**Review by Revolyssup — APPROVED** [review]
LGTM

**Comment by Revolyssup** [comment]
> @Revolyssup can you see this one through?

Merge this and then also merge this https://github.com/meshery/meshery-istio/pull/311

**Review by DelusionalOptimist — APPROVED** [review]
Thanks for updating this @sayantan1413 :+1:

**Comment by leecalcote** [comment]
Thanks for seeing this through, guys.

**Pull request merged**
