### PR TITLE
[CI] Remove $ in e2e test workflow

### PR DESCRIPTION
**Pull request by leecalcote**
**Description**

See https://github.com/meshery/meshery-istio/actions/runs/1634869405 as an example run of this proposed change.

### CODE REVIEW

**Review by alphaX86 — APPROVED** [review]
LGTM

**Comment by leecalcote** [comment]
Thank you, @alphaX86

**Comment by leecalcote** [comment]
Ready for this to be propagated across other adapters...

**Comment by leecalcote** [comment]
@Shreyas220 @iamsdas either you might want to assist in propagating this change across the rest of the adapters.

**Pull request merged**
