### PR TITLE
changed istio apis

### LINKED ISSUE #249: Move from `/api/experimental/oam` to `/api/oam`
**Current Behavior**
Currently istio adapter sends request to `/api/experimental/oam/workload` and `/api/experimental/oam/trait` in order to register its capabilities. 

**Desired Behavior**
https://github.com/meshery/meshery/pull/3542 will deprecate these endpoints in favour of  `/api/oam/workload` and `/api/oam/trait`. Istio adapter should adhere to the latest API changes in meshery server.

**Acceptance Tests**
- [ ] Replace all `/api/experimental/oam/workload` with `/api/oam/workload`
- [ ] Replace all `/api/experimental/oam/trait` with `/api/oam/trait`

### PR DESCRIPTION
**Pull request by umairnsr87**
**Description**

This PR fixes #249 

**Notes for Reviewers**
changed /api/experimental/oam/workload to /api/oam/workload
changed /api/experimental/oam/trait to /api/oam/trait

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by umairnsr87** [comment]
@utkarsh-pro  can you please review changes?

**Review by utkarsh-pro — APPROVED** [review]
LGTM, thanks :+1:

**Comment by umairnsr87** [comment]
Thanks alot @utkarsh-pro  for being a helping hand.....reallly appreciate it... :1st_place_medal:

**Comment by leecalcote** [comment]
@piyushsingariya in terms of timing... are we ok to publish a release here?

**Comment by piyushsingariya** [comment]
Yes we are!

**Pull request merged**
