### PR TITLE
Slack notification

### PR DESCRIPTION
**Pull request by theBeginner86**
Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>

**Description**
It fixes the slack notification for new stargazers on this repo.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks, Pranav. Will you ensure that this is a copy of the slack workflow from the a Meshery repo? The github.actor and other items should be included.

**Comment by theBeginner86** [comment]
I'll do it.
But I'm afraid, I cannot understand what you meant by `github.actor and other items should be included` 😅
I believe that those items are already there on line 16. Please correct me if I'm wrong. Actually I'm still exploring these terminologies.

**Comment by leecalcote** [comment]
@theBeginner86 review this line - https://github.com/meshery/meshery/blob/080ee07c1ffe306cef90b5e6a86d0229a23f27ce/.github/workflows/slack.yml#L17

**Comment by theBeginner86** [comment]
Thanks @leecalcote for providing that link

I still couldn't find what is missing 😨

For your reference:
- Screenshot of my change:
Screenshot 2021-11-23 at 9 59 48 AM


- Screenshot of the file your shared:
Screenshot 2021-11-23 at 10 15 22 AM

I still believe that the line 16 on [file](https://github.com/meshery/meshery-istio/pull/303/files#) of this PR and last line on [file](https://github.com/meshery/meshery/blob/080ee07c1ffe306cef90b5e6a86d0229a23f27ce/.github/workflows/slack.yml#L17) you shared are similar(only repo links and names are different).

**Comment by leecalcote** [comment]
@theBeginner86, you're right. Of the item that I described, that concern is already addressed and needs no change here. 👍 

I do have another ask to consider: using a variable for the repo name, so that this same `slack.yaml` workflow can be exactly the same across all repos. (e.g. `GITHUB_REPOSITORY`) - https://docs.github.com/en/actions/learn-github-actions/environment-variables. If you would like to undertake this, will you crack open a new issue?

**Pull request merged**
