### PR TITLE
Change format for date and SHA (for filenames)

### PR DESCRIPTION
**Pull request by alphaX86**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]

**Comment by alphaX86** [comment]
Ok.... this needs a thorough analysis and come with a new method to resolve this

**Comment by leecalcote** [comment]
@alphaX86 wait... did it fail? I canceled a couple of the runs because they were redundant.

**Comment by leecalcote** [comment]
oh, yes, it did - https://github.com/meshery/meshery-istio/runs/4660125687?check_suite_focus=true

**Comment by alphaX86** [comment]
> @alphaX86 wait... did it fail? I canceled a couple of the runs because they were redundant.

It indeed failed :') 💆‍♂️

**Comment by alphaX86** [comment]
Ok I found an alt method to do this... 
image

I'll open up a PR one last time to do this... Hope it works... 🤞

**Comment by leecalcote** [comment]
Oh, interesting. Seeing that this works now makes sense.

**Pull request merged**
