### PR TITLE
Add missing custom component files 

### LINKED ISSUE #574: Add missing custom component files
#### Current Behavior

Currently some istio custom component files (`istiomesh` ,`grafanaddon`, `prometheusaddon`,`zipkiniaddon`, `jaegaraddon`)are missing across all meshmodel/component versions.
#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v
- **Meshery Adapter Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### LINKED ISSUE #583: [bug] IstioMesh components not being registered
#### Current Behavior

Istio Service Mesh components are not being registered under Istio Model.

This has too following side affects.
1. Istio Service Mesh component not available for users of [Meshery](https://github.com/meshery/meshery) when they configure their infrastructure.
2. All [e2e tests](https://github.com/meshery/meshery-istio/actions/workflows/e2etests.yml) failing.

#### Expected Behavior

Istio Service Mesh components must be registered under Istio Model.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v
- **Meshery Adapter Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by ayushthe1**
**Description**

This PR fixes #574 and fixes #583

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@ayushthe1 add a reviewer, please. add appropriate labels, too, please.

**Comment by ayushthe1** [comment]
@leecalcote I don't have the permissions to do that.  Could you please add it.

**Comment by Aisuko** [comment]
Hi, guys. There are tons of files and are hard to review.

**Comment by leecalcote** [comment]
@ayushthe1 you do have permission to manage issue labels...

@Aisuko you're right. It's completely overwhelming.

**Comment by Azanul** [comment]
@ayushthe1 Many JSONs are differently formatted; could you get them to be consistent?

**Comment by Azanul** [comment]
@leecalcote This either requires a validation script or merge and see whether it's all fine or not.

**Comment by gyohuangxin** [comment]
@ayushthe1 Is there any new update, can we keep going? Thanks.

**Comment by theBeginner86** [comment]
Updated the model name

**Comment by gyohuangxin** [comment]
There are still some failed CI tests, @theBeginner86 do you know how to resolve this?

**Comment by theBeginner86** [comment]
I added the missing model name in https://github.com/service-mesh-patterns/service-mesh-patterns/pull/106

**Comment by theBeginner86** [comment]
This PR https://github.com/service-mesh-patterns/service-mesh-patterns/pull/107 would solve the last set of tests that checks the sample apps.

**Comment by theBeginner86** [comment]
updated filename reference for sample app design to bookInfo.yaml

**Comment by theBeginner86** [comment]
https://github.com/service-mesh-patterns/service-mesh-patterns/pull/108

**Comment by theBeginner86** [comment]
All ✅

Lets merge this

**Comment by gyohuangxin** [comment]
Thank you for your efforts to resolve this issue !👍  Which release will contain this patch and when will it happen?

**Comment by theBeginner86** [comment]
> Thank you for your efforts to resolve this issue !👍 Which release will contain this patch and when will it happen?

Its already released in latest meshery-istio adapter. https://github.com/meshery/meshery-istio/releases/tag/v0.6.11

**Comment by gyohuangxin** [comment]
@theBeginner86 I've updated meshery-istio to v0.6.11, 
image

and this is my pattern yaml file:
```
name: Istio Installation with CryptoMB
services:
  istioservicemesh:
    name: istioservicemesh
    type: IstioMesh
    model: ISTIO
    namespace: "istio-system"
    settings:
      profile: default
      version: 1.17.2
    traits:
      components:
        ingressGateways:
        - enabled: true
          name: istio-ingressgateway
          k8s:
            overlays:
              - kind: Deployment
                name: istio-ingressgateway
                patches:
                - path: spec.template.spec.containers.[name:istio-proxy].args.[-1]
                  value: "--concurrency=4"
            # Limit CPU/MEM usage to 4 vCPUs/4 GB for QoS reasons.
            # Enable CPU manager static policy in kubelet to even more deterministic results.
            resources:
              requests:
                cpu: 4000m
                memory: 4096Mi
              limits:
                cpu: 4000m
                memory: 4096Mi
            hpaSpec:
              maxReplicas: 1
              minReplicas: 1
            podAnnotations: # this controls the SDS service which configures ingress gateway
              proxy.istio.io/config: |
                privateKeyProvider:
                  cryptomb:
                    pollDelay: 10ms
      automaticSidecarInjection:
        namespaces:
        - default
      meshmap:
        edges: []
        id: istioservicemesh
        label: istioservicemesh
        position:
          posX: 59.458251455094434
          posY: 5.53595199333449
```
but it still failed with error: 
image

Is there something wrong with my configuration? Could you please give me an example for that?

**Comment by Revolyssup** [comment]
> @theBeginner86 I've updated meshery-istio to v0.6.11, image
> 
> and this is my pattern yaml file:
> 
> ```
> name: Istio Installation with CryptoMB
> services:
>   istioservicemesh:
>     name: istioservicemesh
>     type: IstioMesh
>     model: ISTIO
>     namespace: "istio-system"
>     settings:
>       profile: default
>       version: 1.17.2
>     traits:
>       components:
>         ingressGateways:
>         - enabled: true
>           name: istio-ingressgateway
>           k8s:
>             overlays:
>               - kind: Deployment
>                 name: istio-ingressgateway
>                 patches:
>                 - path: spec.template.spec.containers.[name:istio-proxy].args.[-1]
>                   value: "--concurrency=4"
>             # Limit CPU/MEM usage to 4 vCPUs/4 GB for QoS reasons.
>             # Enable CPU manager static policy in kubelet to even more deterministic results.
>             resources:
>               requests:
>                 cpu: 4000m
>                 memory: 4096Mi
>               limits:
>                 cpu: 4000m
>                 memory: 4096Mi
>             hpaSpec:
>               maxReplicas: 1
>               minReplicas: 1
>             podAnnotations: # this controls the SDS service which configures ingress gateway
>               proxy.istio.io/config: |
>                 privateKeyProvider:
>                   cryptomb:
>                     pollDelay: 10ms
>       automaticSidecarInjection:
>         namespaces:
>         - default
>       meshmap:
>         edges: []
>         id: istioservicemesh
>         label: istioservicemesh
>         position:
>           posX: 59.458251455094434
>           posY: 5.53595199333449
> ```
> 
> but it still failed with error: image
> 
> Is there something wrong with my configuration? Could you please give me an example for that?

Can you share the logs of istio adapter?

**Comment by Revolyssup** [comment]
@gyohuangxin  Did you create the above configuration from Meshmap or is it handtyped

**Comment by gyohuangxin** [comment]
@Revolyssup I handtyped it, and I didn't see any logs in Istio adapter, the error happened in meshery main process:
```
meshery-meshery-1        | time="2023-06-12T05:51:21Z" level=info msg="kubernetes contexts successfully retrieved from remote provider"
meshery-meshery-1        | time="2023-06-12T05:51:21Z" level=info msg="attempting to fetch patterns resource from cloud"
meshery-meshery-1        | time="2023-06-12T05:51:21Z" level=info msg="pattern resources successfully retrieved from remote provider"
meshery-meshery-1        | map[string]interface {}{"name":"Istio Installation with CryptoMB", "services.istioservicemesh.id":"47565a89-f7c3-4d76-9304-10c8d67fd999", "services.istioservicemesh.model":"ISTIO", "services.istioservicemesh.name":"istioservicemesh", "services.istioservicemesh.namespace":"istio-system", "services.istioservicemesh.settings.profile":"default", "services.istioservicemesh.settings.version":"1.17.2", "services.istioservicemesh.traits.automaticSidecarInjection.namespaces.0":"default", "services.istioservicemesh.traits.components.ingressGateways.0.enabled":true, "services.istioservicemesh.traits.components.ingressGateways.0.k8s.hpaSpec.maxReplicas":1, "services.istioservicemesh.traits.components.ingressGateways.0.k8s.hpaSpec.minReplicas":1, "services.istioservicemesh.traits.components.ingressGateways.0.k8s.overlays.0.kind":"Deployment", "services.istioservicemesh.traits.components.ingressGateways.0.k8s.overlays.0.name":"istio-ingressgateway", "services.istioservicemesh.traits.components.ingressGateways.0.k8s.overlays.0.patches.0.path":"spec.template.spec.containers.[name:istio-proxy].args.[-1]", "services.istioservicemesh.traits.components.ingressGateways.0.k8s.overlays.0.patches.0.value":"--concurrency=4", "services.istioservicemesh.traits.components.ingressGateways.0.k8s.podAnnotations.proxy.istio.io/config":"privateKeyProvider:\n  cryptomb:\n    pollDelay: 10ms\n", "services.istioservicemesh.traits.components.ingressGateways.0.k8s.resources.limits.cpu":"4000m", "services.istioservicemesh.traits.components.ingressGateways.0.k8s.resources.limits.memory":"4096Mi", "services.istioservicemesh.traits.components.ingressGateways.0.k8s.resources.requests.cpu":"4000m", "services.istioservicemesh.traits.components.ingressGateways.0.k8s.resources.requests.memory":"4096Mi", "services.istioservicemesh.traits.components.ingressGateways.0.name":"istio-ingressgateway", "services.istioservicemesh.traits.meshmap.id":"istioservicemesh", "services.istioservicemesh.traits.meshmap.label":"istioservicemesh", "services.istioservicemesh.traits.meshmap.position.posX":59.458251455094434, "services.istioservicemesh.traits.meshmap.position.posY":5.53595199333449, "services.istioservicemesh.type":"IstioMesh"}
meshery-meshery-1        | IstioMesh ISTIO
meshery-meshery-1        | time="2023-06-12T05:51:21Z" level=error msg="could not find component with name: IstioMesh, model: ISTIO, apiVersion: "
meshery-meshery-1        | time="2023-06-12T05:51:21Z" level=error msg="could not find component with name: IstioMesh, model: ISTIO, apiVersion: " app=meshery code=2012 probable-cause= severity=2 short-description="unable to Create Comp Config..could not find component with name: IstioMesh, model: ISTIO, apiVersion: " suggested-remediation=
```

**Pull request merged**
