### PR TITLE
Change none to edge

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Revolyssup** [comment]
@sayantan1413  Can you make this change across all the adapters? Just have to change this one line everywhere.
none->edge

**Review by leecalcote — APPROVED** [review]
LGTM

**Comment by leecalcote** [comment]
> @sayantan1413 Can you make this change across all the adapters? Just have to change this one line everywhere.
> none->edge

@asubedy FYI

**Comment by asubedy** [comment]
Sorry, @leecalcote I didn’t get this 😢 . Is there something to be done from my end? 😬

**Comment by leecalcote** [comment]
@asubedy only to take @Revolyssup up on his offer for helping propagate this change to other adapters.

**Comment by asubedy** [comment]
Oh ok, on it. 👍

**Pull request merged**
